export const users = [
  {
    id: 1,
    pic: "/img/1.jfif",
    username: "James John",
  },
  {
    id: 2,
    pic: "/img/2.jfif",
    username: "Thomas Edward",
  },
  {
    id: 3,
    pic: "/img/3.jfif",
    username: "Daniel Rebort",
  },
  {
    id: 4,
    pic: "/img/6.jfif",
    username: "Michael Paul",
  },
  {
    id: 5,
    pic: "/img/7.jfif",
    username: "William mark",
  },
  {
    id: 6,
    pic: "/img/8.jfif",
    username: "David donald",
  },
  {
    id: 7,
    pic: "/img/9.jfif",
    username: "George Jeff",
  },
  {
    id: 8,
    pic: "/img/10.jfif",
    username: "Charles kenneth",
  },
  {
    id: 9,
    pic: "/img/11.jfif",
    username: "Mark Ronald",
  },
  {
    id: 10,
    pic: "/img/12.jfif",
    username: "kieven jason",
  },
  {
    id: 11,
    pic: "/img/13.jfif",
    username: "michael antony",
  },
  {
    id: 12,
    pic: "/img/14.jfif",
    username: "Steven Chrestopher",
  },
  {
    id: 13,
    pic: "/img/15.jfif",
    username: "Robert jason",
  },
  {
    id: 14,
    pic: "/img/16.jfif",
    username: "paul jiff",
  },
  {
    id: 15,
    pic: "/img/17.jfif",
    username: "Georgr william",
  },
  {
    id: 16,
    pic: "/img/18.jfif",
    username: "Charles kenneth",
  },
];
//*************************************************************************
export const posts = [
  {
    id: "1",
    desc: "Hello there do you think that pic is awesome",
    photo: "/assets/1.jfif",
    date: "5 min ago",
    userid: "1",
    like: 49,
    comment: "20",
  },
  {
    id: "2",
    desc: "opinion!",
    photo: "/assets/2.jfif",
    date: "17 min ago",
    userid: "2",
    like: 33,
    comment: "35",
  },
  {
    id: "3",
    desc: "do you thinK!!?",
    photo: "/assets/3.jfif",
    date: "23 min ago",
    userid: "3",
    like: 50,
    comment: "33",
  },
  {
    id: "4",
    desc: "I am not sure do you think I can do it",
    photo: "/assets/4.jfif",
    date: "9 min ago",
    userid: "4",
    like: 13,
    comment: "7",
  },
  {
    id: "5",
    desc: "sorry I think I am better than you enjoy",
    photo: "/assets/5.jfif",
    date: "1 h ago",
    userid: "5",
    like: 70,
    comment: "50",
  },
  {
    id: "6",
    desc: "",
    photo: "/assets/6.jfif",
    date: "3 h  ago",
    userid: "6",
    like: 23,
    comment: "15",
  },
  {
    id: "7",
    desc: "tell me do you like?!",
    photo: "/assets/7.jfif",
    date: "2 days ago",
    userid: "7",
    like: 90,
    comment: "45",
  },
  {
    id: "8",
    desc: "give me like if you love me",
    photo: "/assets/8.jfif",

    date: "19 min ago",
    userid: "8",
    like: 150,
    comment: "113",
  },
  {
    id: "9",
    desc: "Do you think I am great Front End Developer!!",
    photo: "/assets/9.jfif",

    date: "20 min ago",
    userid: "9",
    like: 450,
    comment: "600",
  },
  {
    id: "10",
    desc: "no caption",
    photo: "/assets/10.jfif",
    date: "50 min ago",
    userid: "10",
    like: 76,
    comment: "48",
  },
  {
    id: "11",
    desc: "",
    photo: "/assets/11.jfif",

    date: "40 min ago",
    userid: "11",
    like: 5,
    comment: "1",
  },
  {
    id: "12",
    desc: "wow what a great pic!!",
    photo: "/assets/12.jfif",
    date: "6 h ago",
    userid: "12",
    like: 40,
    comment: "50",
  },
  {
    id: "13",
    desc: "wow!!!",
    photo: "/assets/13.jfif",

    date: "6 min ago",
    userid: "13",
    like: 49,
    comment: "22",
  },
  {
    id: "14",
    desc: "I think that would inspire you my friend",
    photo: "/assets/14.jfif",

    date: "1 day ago",
    userid: "14",
    like: 78,
    comment: "47",
  },
  {
    id: "15",
    desc: "no caption again",
    photo: "/assets/15.jfif",

    date: "44 min ago",
    userid: "15",
    like: 102,
    comment: "99",
  },
  {
    id: "16",
    desc: "What!!",
    photo: "/assets/16.jfif",
    date: "26 min ago",
    userid: "16",
    like: 200,
    comment: "145",
  },
];
